### PR TITLE
chore(ionic): update to v7

### PR DESCRIPTION
**Pull request by brandyscarney**
- updates to Ionic v7
- does NOT update input syntax

### CODE REVIEW

**Comment by liamdebeasi** [comment]
> DOCS: It is not clear how swipeToClose becomes canDismiss for the card modal

In this case you can just remove `swipeToClose` since card modals are swipeable by default. If you wanted to prevent swiping then you can use `canDismiss`. I'll update the migration guide to clarify this.

> DOCS: Where is the documentation for the input syntax changes?

Input syntax changes are here: https://ionicframework.com/docs/v7/api/input#migrating-from-legacy-input-syntax

> BUG: In the datetime example, in md mode, the bottom of the Location is cutoff (exists in v6 too)

If you use the new input syntax then the highlight goes away inside of ion-item.

**Comment by brandyscarney** [comment]
> Input syntax changes are here: https://ionicframework.com/docs/v7/api/input#migrating-from-legacy-input-syntax

Can we add this (and the checkbox, toggle, etc.) somewhere in the migration guide here: https://ionicframework.com/docs/v7/updating/7-0

There are warnings in the console about it but it's kind of hard to find these docs

**Comment by liamdebeasi** [comment]
I don't think adding them to the migration guide is the right call here. The migration guide only notes the changes that developers need to make in order to have a working version of Ionic 7. The input syntax changes are optional at the moment, so devs don't need to make those changes.

Would it help if we linked to the docs from the console warning?

**Comment by brandyscarney** [comment]
> Would it help if we linked to the docs from the console warning?

Yeah that would be fine

**Comment by brandyscarney** [comment]
I was going to do the input syntax changes but I am not sure how to approach some of them, like this: https://github.com/ionic-team/docs-demo/blob/56b246d718d632d5039eaca7c63a9ad17d0ec836/src/components/input/input.tsx#L53-L60

Want me to make a tech debt ticket for this and leave it for now?

**Comment by liamdebeasi** [comment]
Sure you can make a tech debt ticket. For those inputs you'd want to add an `aria-label` to each and that should be sufficient.

**Comment by brandyscarney** [comment]
Done: https://ionic-cloud.atlassian.net/browse/FW-3796

Is our plan to merge these immediately or wait until the 7.0 release?

**Comment by liamdebeasi** [comment]
You can merge this now because the deployment is configured to only show up on the v7 docs.

**Pull request merged**
